### ISSUE TITLE
individual sample IDs?

### ISSUE THREAD

**Issue by barneyhill** [benjeffery/tsinfer-snakemake#17]
Does this pipeline preserve the individual ID's from the vcf file? I've just noticed that it doesn't seem to have carried over in my individual metadata from my inferred ts.

```
Individual(id=0, flags=0, location=array([], dtype=float64), parents=array([], dtype=int32), nodes=array([0, 1], dtype=int32), metadata={'sample_data_time': nan})
```

**Comment by benjeffery** [comment]
I'll look into this, it certainly should!

**Comment by barneyhill** [comment]
Do you know whereabouts I should look to fix this issue?

**Comment by benjeffery** [comment]
This should be handled in tsinfer: https://github.com/tskit-dev/tsinfer/issues/871

**Comment by benjeffery** [comment]
@barneyhill this is now fixed in tsinfer `main` let me know if the fix works for you
