### ISSUE TITLE
DAG build time

### ISSUE THREAD

**Issue by barneyhill** [benjeffery/tsinfer-snakemake#33]
Since `match_sample_paths` is parameterised by samples and I have ~900,000 samples, the DAG takes quite a long time to build. I'll create a fork and see if using snakemake's built-in rule dependency improves the DAG build time (https://stackoverflow.com/questions/64794407/snakemake-slowing-down-exponentially-due-to-large-amount-of-files-being-processe)

**Comment by benjeffery** [comment]
What `slice_size` are you using? Bumping this up will reduce the number of snakemake tasks.

**Comment by barneyhill** [comment]
Made some changes but didn't seem to have much effect and just seemed more complex - closing
